name: Build image
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-image:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_USERNAME: gitea
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i
      - name: Build
        run: |
          bun run build
      
      - name: Release
        uses: tobua/release-npm-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN  }}
          NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
          